const $=(selector)=>document.querySelector(selector);
function parseCouncilDate(value){const[day,month,year]=value.split('/').map(Number);return new Date(year,month-1,day,12)}
function startOfToday(){const now=new Date();return new Date(now.getFullYear(),now.getMonth(),now.getDate(),12)}
function daysUntil(date){return Math.round((date-startOfToday())/86400000)}
function relativeLabel(date){const days=daysUntil(date);return days===0?'Today':days===1?'Tomorrow':`In ${days} days`}
function cleanService(service){if(service.startsWith('Garden waste'))return'Garden waste';if(service.startsWith('Clothes, textiles'))return'Textiles & small electricals';return service}
function serviceDetails(services){const recycling=services.includes('Recycling');const refuse=services.includes('Refuse');return{title:recycling?'Recycling collection':refuse?'Refuse collection':'Bin collection',symbol:recycling?'♻️':refuse?'🗑️':'🚛'}}
function renderNext(record){const date=parseCouncilDate(record.date);const details=serviceDetails(record.services);$('#relative-date').textContent=relativeLabel(date);$('#collection-date').textContent=date.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'});$('#bin-symbol').textContent=details.symbol;$('#services').replaceChildren(...record.services.map(service=>{const badge=document.createElement('span');badge.className='service';badge.textContent=cleanService(service);return badge}));const days=daysUntil(date);$('#put-out').textContent=days===1?'Put the bins out this evening.':`Your evening reminder will arrive ${days>1?'the night before':'as usual'}.`;$('#loading').hidden=true;$('#next-collection').hidden=false}
function renderUpcoming(records){const future=records.filter(record=>parseCouncilDate(record.date)>=startOfToday()).slice(0,4);$('#upcoming').replaceChildren(...future.map(record=>{const date=parseCouncilDate(record.date);const details=serviceDetails(record.services);const item=document.createElement('article');item.className='upcoming-item';item.innerHTML=`<div class="date-tile"><strong>${date.getDate()}</strong><span>${date.toLocaleDateString('en-GB',{month:'short'}).toUpperCase()}</span></div><div class="upcoming-copy"><strong>${details.title}</strong><span>${record.services.map(cleanService).join(' · ')}</span></div><div class="upcoming-emoji" aria-hidden="true">${details.symbol}</div>`;return item}))}
async function loadSchedule(){try{const response=await fetch('./data/schedule.json',{cache:'no-store'});if(!response.ok)throw new Error(`Schedule request failed: ${response.status}`);const data=await response.json();const future=data.collections.filter(record=>parseCouncilDate(record.date)>=startOfToday());if(!future.length)throw new Error('No future collections');renderNext(future[0]);renderUpcoming(future);$('#updated').textContent=`Updated ${new Date(data.generatedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}`}catch(error){console.error(error);$('#loading').hidden=true;$('#error').hidden=false}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');loadSchedule();
